# syntax=docker/dockerfile:1.4

# stage: native

FROM ghcr.io/vapourcontainers/plugin-build-base:latest AS native

RUN <<EOF
set -eux
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs
EOF

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/native/package.json ./packages/native/

RUN npm ci

COPY packages/native ./packages/native
RUN <<EOF
set -eux
npm -w @vscloud/native run build
mv ./packages/native/build/Release/vscloud_native.node ./packages/native/build/
EOF

# stage: frontend

FROM node:20-bookworm AS frontend

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/native/package.json ./packages/native/
COPY packages/frontend/package.json ./packages/frontend/

RUN npm ci

COPY --link --from=native /app/packages/native/lib ./packages/native/lib

CMD ["npm", "-w", "@vscloud/frontend", "run", "dev"]

# stage: server

FROM node:20-bookworm AS server

RUN <<EOF
set -eux
echo "deb http://www.deb-multimedia.org bookworm main" >> /etc/apt/sources.list
apt-get update -oAcquire::AllowInsecureRepositories=true
apt-get install -y --allow-unauthenticated --no-install-recommends deb-multimedia-keyring vapoursynth
apt-get autoremove -y --purge
apt-get clean
rm -rf /var/lib/apt/lists/*
mkdir -p $HOME/.config/vapoursynth
echo "UserPluginDir=/usr/local/lib/vapoursynth" > $HOME/.config/vapoursynth/vapoursynth.conf
EOF

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/native/package.json ./packages/native/
COPY packages/server/package.json ./packages/server/

RUN npm ci

COPY --link --from=native /app/packages/native/build/*.node ./packages/native/build/
COPY --link --from=native /app/packages/native/lib ./packages/native/lib

CMD ["npm", "-w", "@vscloud/server", "run", "dev"]
